version: '3.8'

services:
  trends-api:
    build: .
    ports:
      - "8081:8081"
    restart: always
    container_name: trends_api_container
    environment:
      - EUREKA_URL=http://eureka-server:8761
    networks:
      - platform-network

networks:
  platform-network:
    external: true